### ISSUE TITLE
dependency of concurrent-ruby

### ISSUE THREAD

**Issue by rjayroach** [mikhailvs/rack-fluentd-logger#2]
Hi. Thanks for writing this gem!

We are trying to use it with a Rails 5 app. The problem is that rails pins concurrent-ruby to ~> 1.0 whereas your gem is ~> 1.1

I don't know much about concurrent-ruby. Might it be possible to require ~> 1.0 in your gem?

Thanks!

**Comment by mikhailvs** [comment]
Hey, good suggestion. I merged your PR and relaxed the requirement for concurrent-ruby (pushed an updated version to rubygems as well).
