### ISSUE TITLE
require 'concurrent' vs. 'concurrent-ruby'?

### ISSUE THREAD

**Issue by rjayroach** [mikhailvs/rack-fluentd-logger#4]
Thanks for merging the PR and updating the gemspec. So it is installing fine into the rails app now, however it raises an exception on line 5 of lib/rack/fluentd_logger.rb which is `require 'concurrent-ruby'`. Concurrent's README says the line is `require 'concurrent'` and when I change it to 'concurrent' it loads just fine. I would do a PR  but since you've released it, it must work for you as is. thoughts?

**Comment by mikhailvs** [comment]
Oh man. Sorry about that. My local version was still 1.1, which has the 'concurrent-ruby' file (https://github.com/ruby-concurrency/concurrent-ruby/commit/714d9196850c7157297975e2c88db5cc4fd881e0).


It's updated now to use `require 'concurrent'`
