### ISSUE TITLE
NameError Uninitialized Constant "Error"

### ISSUE THREAD

**Issue by duanshiqiang** [mikhailvs/rack-fluentd-logger#5]
I tried to integrate this middleware with our Rails application, below is the code I used to add the middleware:

```ruby
require 'rack/fluentd_logger'

Rack::FluentdLogger.configure(
  name: Rails.configuration.fluentd.request_logs.name,
  host: Rails.configuration.fluentd.request_logs.host,
  port: Rails.configuration.fluentd.request_logs.port
)

Rails.application.config.middleware.insert 0, Rack::FluentdLogger
```

After starting fluentd with a debug config like below:

```
<source>
  @type forward
  port 24224
</source>

<match **>
  @type stdout
</match>
```

Nothing appears.

After manually modified this gem by adding some debug lines and wrap some code with rescue, it seems it's because of a NameError Uninitialized Constant "Error" at [line 57](https://github.com/mikhailvs/rack-fluentd-logger/blob/master/lib/rack/fluentd_logger.rb#L57):

```
      return format_response_error(response) if response.is_a?(Error)
```

It seems the "Error" class is not found.

**Comment by duanshiqiang** [comment]
Code block posted to the executor (Concurrent::SingleThreadExecutor) doesn't have any visibility. Exception just got swallowed. It's better to have exception log code.

**Comment by duanshiqiang** [comment]
We have switched to an older gem version 0.1.0 and now it works.

**Comment by mikhailvs** [comment]
Hello. Thanks for bringing this to my attention. That line should be checking `is_a?(Exception)` and I'm pushing out an update to correct this.

the `call(env)` method submits either the response from the rest of the rack application, or whatever exception is thrown to fluentd. Are you suggesting that exceptions get logged elsewhere in addition to just being submitted to fluentd?

**Comment by duanshiqiang** [comment]
@mikhailvs Thanks for the quick fix! 

What I suggest the code in the ensure block should have more logs. Currently, if there's an exception like this one, users won't get noticed because it's out of the scope of a HTTP request (from my understanding and I may be wrong).

**Comment by mikhailvs** [comment]
Not completely sure I understand your concern, but sounds like you are worried that if an exception is thrown, this middleware will swallow it without letting the user know it happened.

This will not happen. The ensure block in the method is different from doing a begin-rescue block. Ensure will run despite an exception happening (in order to log it to fluentd), and the exception will continue it's way up the call stack until some other thing catches it.

Here's a simple example of the concept: https://repl.it/@mikhailvs/Ensure-Demo
